Cucumber-TestNg Webdriver Integration
BrowserStackCE/browserstack-examples-aa-cucumber-testng pull request #1
Opened 2021-11-22 11:14 UTC by Rushabhshroff

2021-11-22 15:56 UTC, samirans89 requested changes

2021-11-22 15:56 UTC, samirans89 commented on README.md
> +This repository allows you to to use configuration files similar to the following to run your Appium tests on various platforms including on-premise devices, devices running on an on-prem grid or rem
`remote elenium grid.` - Typo.
Do we want to mention Appium? 
Also do we want to call out that only cloud config has been implemented.

2021-11-22 15:56 UTC, samirans89 commented on README.md
> +The above is just an example. You can use any of hash/custom/shareable ID for your Android/iOS apps.
do we want to mention hash id OR custom id OR shareable ID. As in, my understanding is that only one of them is needed.

2021-11-22 15:56 UTC, samirans89 commented on README.md
> +The above is just an example. You can use any of hash/custom/shareable ID for your Android/iOS apps.
also, which one is chosen if all the IDs are present?

2021-11-22 15:56 UTC, samirans89 commented on pom.xml
> +<!--    </dependency>-->
Do we want to state - We can uncomment these lines once the maven dependency version with AA is uploaded in Maven or something similar

2021-11-22 15:56 UTC, samirans89 commented on src/test/resources/capabilities.yml
> +        appActivity: com.browserstack.sampeapp.MainActivity
If we do not have constraint on the app name and activity, can we update `sampeapp` to `sampleapp`

2021-11-22 15:58 UTC, arvind1998 commented on src/test/resources/capabilities.yml
> +        appActivity: com.browserstack.sampeapp.MainActivity
done

2021-11-22 16:13 UTC, arvind1998 commented on pom.xml
> +<!--    </dependency>-->
this isn't required at all. have removed it altogether.

2021-11-22 16:13 UTC, Rushabhshroff commented on README.md
> +The above is just an example. You can use any of hash/custom/shareable ID for your Android/iOS apps.
Hash Id is given preference over Custom ID or Sharable ID

2021-11-22 16:16 UTC, arvind1998 commented on README.md
> +The above is just an example. You can use any of hash/custom/shareable ID for your Android/iOS apps.
modified

2021-11-22 16:17 UTC, arvind1998 commented on README.md
> +This repository allows you to to use configuration files similar to the following to run your Appium tests on various platforms including on-premise devices, devices running on an on-prem grid or rem
typo fixed. 
haven't added the second part as we haven't tested it out.

2021-11-23 12:29 UTC, anirudha13 approved these changes

2021-11-23 17:04 UTC, arvind1998 commented
@samirans89 , can we merge this now?

2021-11-23 18:39 UTC, samirans89 approved these changes

2021-11-23 18:40 UTC, merged